### ISSUE TITLE
Interesting project

### ISSUE THREAD

**Issue by ipolishchuk** [thumbtack/pgdoctor#10]
Marco,
This is an interesting project, that might be useful to many people. 
A great improvement would be adding some documentation on hot to use pgDoctor. 
Actual usage is not clear without extensive studying of source codes, which would be a brier for adoption.   
Igor

**Comment by ravibhure** [comment]
Agreed @ipolishchuk , I am personally loved this project, but it will be more clear on how to use by reading it careful.
https://stackshare.io/thumbtack/scaling-postgresql-at-thumbtack-load-balancing-and-health-checks.

**Comment by marcoalmeida** [comment]
Do you mean documentation on pgDoctor specifically (install, configure, etc.), or a more thorough description of an actual use case setting up load balancers and replicas?

**Comment by ravibhure** [comment]
Hi @marcoalmeida,
yes, the url specifically for use case but I think [pgdoctor](https://github.com/thumbtack/pgdoctor) project needs to cover through document for install, configure and use case.

**Comment by Shantel444** [comment]
I agree, this project is supposed to be really good. I like using different apps, programs, etc. that help me to take care of my health. I find a possibility to do this on te move to be really great. Thus I order all necessary pills online. Also I read the descriptions of them there (here canadapharmacy.com helps me a lot). And now I've found out about your project. Thanks for sharing! Great job!
